name: quickcalc
description: "A simple calculator with Google Ads."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^6.0.0   # ✅ Google Ads SDK
  math_expressions: ^2.6.0
  firebase_core: ^2.26.0
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.5.0
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
